FLASK_APP='manage.py'
FLASK_ENV=development
SECRET_KEY='you-will-never-guess'
DB_USERNAME=flogger_user
DB_PASSWORD=flogger_password
DB_HOST=localhost
DATABASE_NAME=flogger
MYSQL_ROOT_PASSWORD=rootpass
BLOG_NAME='The Flogger Blog'
BLOG_POST_IMAGES_PATH='/opt/flogger/static/images/uploads'
